# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM quay.io/ascend/cann:8.2.rc1-a3-openeuler22.03-py3.11

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
ARG COMPILE_CUSTOM_KERNELS=1

# Define enviroments
ENV DEBIAN_FRONTED=noninteractive
ENV COMPILE_CUSTOM_KERNELS=${COMPILE_CUSTOM_KERNELS}

RUN yum install -y patch

WORKDIR /workspace

RUN pip config set global.index-url ${PIP_INDEX_URL}

# Install torch and torch-npu
RUN python3 -m pip install torch==2.5.1 torch-npu==2.5.1.post1

# Compile/Install apex
RUN source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    source /usr/local/Ascend/nnal/asdsip/set_env.sh && \
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Ascend/ascend-toolkit/latest/`uname -i`-linux/devlib && \
    git clone -b master https://gitcode.com/ascend/apex.git && \
    cd apex/ && bash scripts/build.sh --python=3.11 && \
    cd apex/dist/ && \
    python3 -m pip install --upgrade apex-0.1+ascend-*.whl

# verl
RUN git clone https://github.com/volcengine/verl.git

# MindSpeed
RUN git clone https://gitcode.com/Ascend/MindSpeed.git && \
    cd MindSpeed && \
    git checkout f6688 && \
    pip install -r requirements.txt && \
    cp -r mindspeed ../verl

# Install vLLM
RUN git clone https://github.com/vllm-project/vllm.git && \
    cd vllm && \
    git checkout v0.9.1 && \
    cp -r vllm ../verl
# In x86, triton will be installed by vllm. But in Ascend, triton doesn't work correctly. we need to uninstall it.
RUN VLLM_TARGET_DEVICE="empty" python3 -m pip install -e /workspace/vllm/ --extra-index https://download.pytorch.org/whl/cpu/ && \
    python3 -m pip uninstall -y triton && \
    python3 -m pip cache purge

# Install vllm-ascend
RUN git clone https://github.com/vllm-project/vllm-ascend.git && \
    cd vllm-ascend && \
    git checkout 8c7bc45 && \
    cp -r vllm_ascend ../verl

# Append `libascebd_hal.so` path (devlib) to LD_LIBRARY_PATH
RUN source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Ascend/ascend-toolkit/latest/`uname -i`-linux/devlib && \
    export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/include/c++/12:/usr/include/c++/12/`uname -i`-openEuler-linux && \
    python3 -m pip install -v -e /workspace/vllm-ascend/ --exists-action=i --extra-index https://download.pytorch.org/whl/cpu/ && \
    python3 -m pip cache purge

# Install modelscope (for fast download) and ray (for multinode) and Megatron-LM and others
RUN python3 -m pip install modelscope ray cache purge "transformers<4.54.0" mathruler cbor2 && \
    pip install pybase64 fastapi zmq uvicorn openai msgspec blake3 py-cpuinfo gguf openai-harmony && \
    pip install git+https://github.com/NVIDIA/Megatron-LM.git@core_v0.12.1

CMD ["/bin/bash"]