task: gsm8k
num_fewshot: 8
metric: exact_match,flexible-extract
description: "GSM8K: easy math transfer benchmark"
gen_kwargs:
  temperature: 0.6
  top_p: 0.95
  do_sample: true
  top_k: 20
  max_gen_toks: 2048
